# Build only the master branch, tagged commits, and pull requests
branches:
  only:
    - master

# Don't run the (redundant) branch build with a pull request
skip_branch_with_pr: true

matrix:
  fast_finish: true

environment:
  PYTHONUNBUFFERED: 1
  COVERAGE_DIR: ""
  MINICONDA: C:\\Miniconda3-x64
  matrix:
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 2.7

install:
  - appveyor DownloadFile https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-win-64.exe -FileName loner_conda.exe
  - set "CONDA_PKGS_DIRS=C:\condacache\pkgs"
  - set "CONDA_ALWAYS_YES=true"
  - set "CONDA_AUTO_UPDATE_CONDA=false"
  - if "%CONDA_CANARY%" == "" (
      loner_conda.exe create -q -p C:\test_conda python=%PYTHON_VERSION% conda=%CONDA_VERSION%
      ) else (
      loner_conda.exe create -q -p C:\test_conda -c conda-canary conda python=%PYTHON_VERSION%
      )
  # Install run dependencies
  - loner_conda.exe install -q -p C:\test_conda conda-build=3.18.10 conda-verify
  # so that the tests see the standalone conda that they need
  - mkdir C:\test_conda\standalone_conda
  - copy loner_conda.exe C:\test_conda\standalone_conda\conda.exe
  - call C:\test_conda\Scripts\activate
  # Install this package
  - python setup.py develop
  # Install conda canary before running tests, ensure conda is updated
  - conda info
  - conda init
  - call C:\test_conda\Scripts\activate
  - conda list

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - call C:\test_conda\Scripts\activate
  - conda build conda.recipe --python=%PYTHON_VERSION%
