name: Build and test the package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install build dependencies
      run: conda install -y -c defaults -c conda-forge conda-build conda-verify codecov flake8 pep257 yapf==0.25.0
    - name: Verify formatting compliance
      run: /usr/share/miniconda/bin/python scripts/run_tests.py --format-only
    - name: Build the package
      run: /usr/share/miniconda/bin/conda build conda.recipe --no-test
    - name: Reduce the size of the build artifact
      run: rm -rf /usr/share/miniconda/conda-bld/{git_cache,work,anaconda-project*,*/.cache}
    - name: Upload the build artifact
      uses: actions/upload-artifact@v2
      with:
        name: package-${{ github.sha }}
        path: /usr/share/miniconda/conda-bld
    - name: Clean up older artifacts
      uses: glassechidna/artifact-cleaner@master
      with:
        minimumAge: 86400
  tests:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    needs: package
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        pyver: [2.7,3.6,3.7,3.8]
        cver: [4.6,4.7,4.8]
        exclude:
          # Cannot instantiate these environment for these yet
          - pyver: 3.8
            cver: 4.6
          - pyver: 3.8
            cver: 4.7
          # Minor test back off to save build time
          - pyver: 3.7
            cver: 4.6
          - pyver: 3.6
            cver: 4.8
          # Aggressive test backoff for Python 2
          - pyver: 2.7
            cver: 4.6
          - pyver: 2.7
            cver: 4.8
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@v2
    - name: Build the conda environment
      run: |
          [ $RUNNER_OS == Windows ] && CONDA_EXE=$CONDA/Scripts/conda.exe
          [ $RUNNER_OS == macOS ] && export CONDA_PKGS_DIRS=~/.pkgs
          [ ${{ matrix.pyver }} == 2.7 ] && TEMPFILE=backports.tempfile
          ${CONDA_EXE:-conda} create -y -p ./conda \
            python=${{ matrix.pyver }} conda=${{ matrix.cver }} \
            $TEMPFILE --file requirements.txt
    - name: Download the build artifact
      uses: actions/download-artifact@v2
      with:
        name: package-${{ github.sha }}
        path: ./conda/conda-bld
    - name: Install the package and run the tests
      run: |
          if [ "$RUNNER_OS" == "Windows" ]; then COVERAGE=98; else COVERAGE=99; fi
          source ./conda/etc/profile.d/conda.sh 
          conda activate base
          conda install -y local::anaconda-project 
          python -m pytest --pyargs -v -rfe --durations=10 \
            --cov-config .coveragerc --cov-report term-missing --no-cov-on-fail \
            --cov-fail-under=$COVERAGE --cov-report html$COVERAGE_DIR \
            --cov anaconda_project anaconda_project
